import { useState, useEffect } from 'react';
import { classesAPI, studentsAPI } from '../../services/api';
import API from '../../services/api';
import { Printer } from 'lucide-react';

export default function PrintAttendance() {
  const [classes, setClasses] = useState([]);
  const [students, setStudents] = useState([]);
  const [selectedClass, setSelectedClass] = useState('');
  const [selectedClassName, setSelectedClassName] = useState('');
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));

  useEffect(() => {
    classesAPI.getAll().then(res => setClasses(res.data.data));
  }, []);

  useEffect(() => {
    if (!selectedClass) return;
    studentsAPI.getAll({ classId: selectedClass }).then(res => setStudents(res.data.data));
    const cls = classes.find(c => c.id === selectedClass);
    setSelectedClassName(cls?.name || '');
  }, [selectedClass]);

  const getDaysInMonth = () => {
    const [year, mon] = month.split('-');
    return new Date(year, mon, 0).getDate();
  };

  const handlePrint = () => {
    const days = getDaysInMonth();
    const [year, mon] = month.split('-');
    const monthName = new Date(year, mon - 1).toLocaleString('default', { month: 'long', year: 'numeric' });

    const html = `<!DOCTYPE html><html><head><title>Attendance Register</title>
    <style>
      body { font-family: Arial, sans-serif; padding: 20px; font-size: 11px; }
      .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #000; padding-bottom: 10px; }
      .school { font-size: 18px; font-weight: bold; }
      .title { font-size: 14px; font-weight: bold; margin-top: 5px; }
      table { width: 100%; border-collapse: collapse; margin-top: 10px; }
      th, td { border: 1px solid #000; padding: 4px; text-align: center; }
      th { background: #f0f0f0; font-weight: bold; }
      .name-col { text-align: left; padding-left: 8px; min-width: 150px; }
      .footer { margin-top: 30px; display: flex; justify-content: space-between; }
      .sign { border-top: 1px solid #000; width: 180px; text-align: center; padding-top: 5px; }
      @media print { body { padding: 10px; } }
    </style></head><body>
    <div class="header">
      <div class="school">Bo Government Secondary School</div>
      <div>Damballa Road, Bo · Sierra Leone</div>
      <div class="title">ATTENDANCE REGISTER — ${selectedClassName}</div>
      <div>${monthName}</div>
    </div>
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th class="name-col">Student Name</th>
          <th>Adm. No.</th>
          ${Array.from({length: days}, (_, i) => `<th>${i+1}</th>`).join('')}
          <th>P</th><th>A</th>
        </tr>
      </thead>
      <tbody>
        ${students.map((s, i) => `
          <tr>
            <td>${i+1}</td>
            <td class="name-col">${s.lastName} ${s.firstName}</td>
            <td>${s.admissionNo}</td>
            ${Array.from({length: days}, () => '<td>&nbsp;</td>').join('')}
            <td></td><td></td>
          </tr>
        `).join('')}
      </tbody>
    </table>
    <div class="footer">
      <div><div class="sign">Class Teacher</div></div>
      <div style="text-align:center;font-size:10px;color:#666;">
        Generated by EduManage SL · Musa Mansaray<br>
        🇸🇱 Republic of Sierra Leone
      </div>
      <div><div class="sign">Principal</div></div>
    </div>
    </body></html>`;

    const win = window.open('', '_blank');
    win.document.write(html);
    win.document.close();
    win.print();
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Print Attendance Sheet</h1>
        <p className="text-gray-500 text-sm mt-1">Generate printable monthly attendance registers</p>
      </div>
      <div className="card space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="label">Select Class</label>
            <select className="input" value={selectedClass} onChange={e => setSelectedClass(e.target.value)}>
              <option value="">Choose class...</option>
              {classes.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
            </select>
          </div>
          <div>
            <label className="label">Month</label>
            <input type="month" className="input" value={month} onChange={e => setMonth(e.target.value)} />
          </div>
        </div>
        {students.length > 0 && (
          <div className="p-4 bg-gray-50 rounded-lg">
            <p className="text-sm text-gray-600">{students.length} students in {selectedClassName}</p>
            <p className="text-xs text-gray-400 mt-1">Ready to print attendance sheet for {month}</p>
          </div>
        )}
        <button onClick={handlePrint} disabled={!selectedClass || students.length === 0}
          className="btn-primary flex items-center gap-2 disabled:opacity-50">
          <Printer className="w-4 h-4" /> Print Attendance Sheet
        </button>
      </div>
    </div>
  );
}