import { useState } from 'react';
import { Printer, CreditCard } from 'lucide-react';
import { feesAPI } from '../../services/api';
import toast from 'react-hot-toast';

const formatSLL = (amount) => `SLL ${Number(amount).toLocaleString()}`;

export default function PrintFeeReceipt() {
  const [fees, setFees] = useState([]);
  const [studentId, setStudentId] = useState('');
  const [loading, setLoading] = useState(false);

  const fetchFees = async () => {
    if (!studentId) return toast.error('Enter student ID');
    setLoading(true);
    try {
      const res = await feesAPI.getAll({ studentId });
      setFees(res.data.data);
      if (res.data.data.length === 0) toast.error('No fees found for this student');
    } catch { toast.error('Failed to load fees'); }
    finally { setLoading(false); }
  };

  const printReceipt = (fee) => {
    const html = `<!DOCTYPE html><html><head><title>Fee Receipt</title>
    <style>
      body { font-family: Arial, sans-serif; padding: 30px; max-width: 400px; margin: 0 auto; }
      .header { text-align: center; border-bottom: 2px solid #1e3a8a; padding-bottom: 15px; margin-bottom: 20px; }
      .school { font-size: 16px; font-weight: bold; color: #1e3a8a; }
      .receipt-title { font-size: 14px; font-weight: bold; margin-top: 8px; background: #1e3a8a; color: white; padding: 5px; }
      .receipt-no { font-size: 12px; color: #666; margin-top: 5px; }
      .info-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; font-size: 13px; }
      .label { color: #666; }
      .value { font-weight: bold; }
      .amount-box { background: #f0fdf4; border: 2px solid #22c55e; border-radius: 8px; padding: 15px; text-align: center; margin: 20px 0; }
      .amount { font-size: 24px; font-weight: bold; color: #166534; }
      .status { font-size: 12px; color: #166534; margin-top: 5px; }
      .footer { text-align: center; margin-top: 20px; font-size: 11px; color: #666; border-top: 1px solid #eee; padding-top: 15px; }
      .signature { border-top: 1px solid #000; width: 150px; margin: 20px auto 0; padding-top: 5px; text-align: center; font-size: 12px; }
      @media print { body { padding: 10px; } }
    </style></head><body>
    <div class="header">
      <div class="school">Bo Government Secondary School</div>
      <div style="font-size:11px;color:#666;">Damballa Road, Bo · Sierra Leone</div>
      <div class="receipt-title">OFFICIAL FEE RECEIPT</div>
      <div class="receipt-no">Receipt No: RCP-${fee.id.slice(-6).toUpperCase()} · ${new Date().toLocaleDateString()}</div>
    </div>
    <div class="info-row"><span class="label">Student Name:</span><span class="value">${fee.student?.firstName} ${fee.student?.lastName}</span></div>
    <div class="info-row"><span class="label">Admission No:</span><span class="value">${fee.student?.admissionNo}</span></div>
    <div class="info-row"><span class="label">Academic Year:</span><span class="value">${fee.academicYear?.year}</span></div>
    <div class="info-row"><span class="label">Term:</span><span class="value">${fee.term} TERM</span></div>
    <div class="info-row"><span class="label">Description:</span><span class="value">${fee.description || 'School Fees'}</span></div>
    <div class="info-row"><span class="label">Due Date:</span><span class="value">${new Date(fee.dueDate).toLocaleDateString()}</span></div>
    <div class="amount-box">
      <div style="font-size:12px;color:#666;margin-bottom:5px;">Amount Paid</div>
      <div class="amount">${formatSLL(fee.amountPaid)}</div>
      <div class="status">of ${formatSLL(fee.amount)} total · Status: ${fee.status}</div>
    </div>
    ${fee.status !== 'PAID' ? `<div style="text-align:center;color:#dc2626;font-size:12px;font-weight:bold;">Outstanding Balance: ${formatSLL(fee.amount - fee.amountPaid)}</div>` : ''}
    <div class="signature">Accounts Officer</div>
    <div class="footer">
      This is an official receipt from Bo Government Secondary School<br>
      Generated by EduManage SL · Designed by Musa Mansaray<br>
      🇸🇱 Republic of Sierra Leone
    </div>
    </body></html>`;

    const win = window.open('', '_blank');
    win.document.write(html);
    win.document.close();
    win.print();
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Fee Receipts</h1>
        <p className="text-gray-500 text-sm mt-1">Print official fee receipts for students</p>
      </div>
      <div className="card space-y-4">
        <div className="flex gap-3">
          <div className="flex-1">
            <label className="label">Student ID</label>
            <input className="input" placeholder="Paste student ID" value={studentId} onChange={e => setStudentId(e.target.value)} />
          </div>
          <div className="mt-5">
            <button onClick={fetchFees} disabled={loading} className="btn-primary">
              {loading ? 'Loading...' : 'Find Fees'}
            </button>
          </div>
        </div>
      </div>

      {fees.length > 0 && (
        <div className="space-y-3">
          {fees.map(fee => (
            <div key={fee.id} className="card hover:shadow-md transition-shadow">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <CreditCard className="w-8 h-8 text-primary-400" />
                  <div>
                    <p className="font-semibold text-gray-900">{fee.student?.firstName} {fee.student?.lastName}</p>
                    <p className="text-sm text-gray-500">{fee.term} Term · {fee.description || 'School Fees'}</p>
                    <p className="text-sm text-green-600 font-medium">Paid: {formatSLL(fee.amountPaid)} / {formatSLL(fee.amount)}</p>
                  </div>
                </div>
                <button onClick={() => printReceipt(fee)} className="btn-primary flex items-center gap-2">
                  <Printer className="w-4 h-4" /> Print Receipt
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}